version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
     - 8081-8082:8081-8082
    volumes:
     - ./data/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - build_tools
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
     - ./data/jenkins/jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - build_tools
  fluentd:
    image: fluentd:latest
    container_name: fluentd
    volumes:
      - ./conf/fluentd:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elk
      - build_tools
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk
  kibana:
    image: kibana:8.6.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - elk
  haproxy:
    hostname: haproxy
    image:  haproxy:latest
    ports:
      - 8888:8888
    volumes:
      - ./conf/haproxy:/usr/local/etc/haproxy:ro
    networks:
      - elk
networks:
  elk:
    driver: bridge
  build_tools:
    driver: bridge  