node {
  try {
    def version = null; 
    def tag = null;
    def gitCommit = null;
    def release = null;
    def repoHost = "artifactory.local"
    def repoName = "fontend_angular"
    
    stage ('Checkout and Tag') {
      checkout scm
      sh 'env'
      gitCommit = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
      release = env.BRANCH_NAME ;
      version = "${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
      tag = "${release}.${env.BUILD_NUMBER}";
      latest = "${env.BRANCH_NAME}-latest";
    }
    stage ('Build docker images') { 
        sh "docker build -t ${repoHost}${repoName}:${tag} -f Dockerfile ."
        sh "docker push ${repoHost}${repoName}:${tag} "
    }

    stage ('Run unitest') {
        //TODO:
    }
    stage ('Use xray to check volonrabilities') {
        //TODO:
    }
    
  } catch (e) {
    throw e
  }
  
}